wps-light support
hyperskill/hyperstyle pull request #17
Opened 2021-03-21 09:50 UTC by GirZ0n

**Issues**:
- Added wps-light support; #2 
- Fixed tests.

2021-04-01 08:11 UTC, dariadiatlova requested changes

2021-04-01 08:11 UTC, dariadiatlova commented on src/python/review/inspectors/flake8/flake8.py
> +        regex_match = re.match(r'^([a-z]+)(\d+)$', code, re.IGNORECASE)
Maybe consider tweaking regex?
regex_match = re.match(r'^([A-Z]+)(\d{1})\d*$', code, re.IGNORECASE) 
In the case above the second group will capture the first code number and can be added to CODE_PREFIX_TO_ISSUE_TYPE as a key (as currently groups are divided by hundreds in ranges). In that case no need to create WPS_RANGE_TO_ISSUE_TYPE and make ‘for’ cycle through the items while handling WPS issues.

2021-04-03 14:04 UTC, dariadiatlova approved these changes

2021-04-03 14:35 UTC, dariadiatlova approved these changes

2021-04-03 15:01 UTC, nbirillo approved these changes
Great job, thanks!

2021-04-03 15:01 UTC, merged