IJ inspector based on code server
hyperskill/hyperstyle pull request #171
Opened 2022-11-15 15:38 UTC by tiginamaria

On this PR we try to support IJ inspections. We implemented a client for the CodeServer - a light IJ running on the server which supports a part of IJ features (e.x. IJ code inspections).

2022-11-16 16:03 UTC, nbirillo requested changes
Great! Also, please redirect the PR into the develop branch

2022-11-16 16:03 UTC, nbirillo commented on hyperstyle/src/python/review/inspectors/ij/ij_inspections.py
> +            code = code_file.read()
We already have a function for it - https://github.com/hyperskill/hyperstyle/blob/main/hyperstyle/src/python/review/common/file_system.py#L99

2022-11-16 16:03 UTC, nbirillo commented on hyperstyle/src/python/review/inspectors/ij/model.py
> +            file_path=Path(),  # TODO: make optional?
Probably you have this path if you call the inspect method with a file

2022-11-17 11:00 UTC, nbirillo approved these changes

2022-11-17 11:07 UTC, merged

2022-11-17 13:02 UTC, andrvb commented on hyperstyle/src/python/review/inspectors/ij/ij_inspections.py
> +                data=IJCode(code, self.languageId).to_json(),
Requests to the external service is better to do with a timeout.