Radon support
hyperskill/hyperstyle pull request #19
Opened 2021-04-06 11:44 UTC by GirZ0n

**Issues**:
- Added new inspector: Radon. #2
- Added maintainability index.

2021-04-07 20:17 UTC, dariadiatlova approved these changes

2021-04-08 11:15 UTC, nbirillo requested changes
Great!

2021-04-08 11:15 UTC, nbirillo commented on src/python/review/inspectors/radon/radon.py
> +            issue_data[IssueData.DESCRIPTION.value] = ""  # TODO: add tip
Why did you not add a tip?

2021-04-12 18:25 UTC, nbirillo approved these changes
Great! Thank you a lot

2021-04-12 18:26 UTC, merged