flake8-spellcheck issues fix
hyperskill/hyperstyle pull request #23
Opened 2021-04-11 12:55 UTC by GirZ0n

**Changes**:
- Added new words to whitelist

**Description**:
I used noqa here b4f8046 because I don't think we need to add the word "nbirillo" to the whitelist

2021-04-11 19:17 UTC, dariadiatlova approved these changes

2021-04-12 18:29 UTC, nbirillo requested changes
Great!

2021-04-12 18:29 UTC, nbirillo commented on src/python/review/quality/model.py
> +    # TODO@nbirillo: why rule.quality_type == quality_type for next level???? # noqa: SC100
I think we can remove nbirillo and then remove noqa: SC100 :)

2021-04-14 08:33 UTC, nbirillo approved these changes
Great, thanks!

2021-04-14 08:34 UTC, merged