Penalty system
hyperskill/hyperstyle pull request #25
Opened 2021-04-27 14:15 UTC by GirZ0n

**Changes**:
- Added penalty system.

**Description**:
- `penalty.py` file contains the functions that make the penalty system work. Each function is described in the documentation.
- `--history` is used to pass previous issues, which takes a JSON string. An example of JSON structure:
``` json
{
   "python":[
      {
         "origin_class":"SC200",
         "quanity":10
      },
      {
         "origin_class":"WPS213",
         "quanity":2
      }
   ]
}
```

2021-04-28 09:31 UTC, dariadiatlova requested changes

2021-04-28 19:10 UTC, dariadiatlova approved these changes

2021-04-29 15:33 UTC, nbirillo requested changes
Great!

2021-04-29 15:33 UTC, nbirillo commented on src/python/review/reviewers/utils/penalty.py
> +def categorize(previous_issues: List[PreviousIssue], current_issues: List[BaseIssue]):
I thnk we need tests

2021-04-29 15:33 UTC, nbirillo commented on src/python/review/reviewers/utils/penalty.py
> +def get_issue_class_to_penalty(issues: List[PreviousIssue]) -> Dict[str, int]:
I need we need tests

2021-04-29 15:33 UTC, nbirillo commented on src/python/review/reviewers/utils/penalty.py
> +common_penalty_rule = PenaltyConfig(
Also, I think we should normalize values and here use something in range [0,1]

2021-04-29 15:33 UTC, nbirillo commented on src/python/review/reviewers/utils/penalty.py
> +        return 3
Please use the default value in the end (without else branch), if you forget to consider a case you will return None, it is incorrect behaviour.

2021-04-29 15:33 UTC, nbirillo commented on src/python/review/quality/model.py
> +    def __init__(self, rules: List[Rule], penalty_coefficient: int = 0):
i think it would be great if you add some description what is penalty_coefficient

2021-04-29 15:33 UTC, nbirillo commented on src/python/review/reviewers/utils/print_review.py
> +            'influence_on_penalty': influence_on_penalty,
Please, change example in main README if you add new field

2021-04-29 15:33 UTC, nbirillo commented on src/python/review/reviewers/utils/print_review.py
> +
You have the same code in the 105-114 lines

2021-05-02 21:52 UTC, meanmail commented on src/python/review/application_config.py
> +    history: str = None
```suggestion
    history: Optional[str] = None
```

2021-05-04 16:57 UTC, nbirillo requested changes
Great! I have several small comments

2021-05-04 16:57 UTC, nbirillo commented on src/python/review/quality/model.py
> +        return type_to_number[self]
Please, add a default value

2021-05-04 16:57 UTC, nbirillo commented on src/python/review/quality/penalty.py
> +class Punisher:
Please, add some description about this class

2021-05-04 16:57 UTC, nbirillo commented on test/python/quality/test_penalty.py
> +def test_get_penalizing_classes_non_empty_intersection_1():
Please, use parameterized tests for several cases with tests with the same logic

2021-05-05 11:06 UTC, nbirillo approved these changes
Great! Thank you

2021-05-05 11:06 UTC, merged