User dynamics
hyperskill/hyperstyle pull request #95
Opened 2021-08-03 12:56 UTC by nbirillo

Add scripts for paper evaluation: user code quality dynamics

2021-08-05 07:06 UTC, GirZ0n requested changes

2021-08-05 07:06 UTC, GirZ0n commented on whitelist.txt
> +ColumnName
I don't think this word is needed on the whitelist

2021-08-09 07:17 UTC, nbirillo commented on src/python/evaluation/evaluation_run_tool.py
> +                         to_drop_nan: bool = True) -> pd.DataFrame:
Sorry, I forgot to delete it

2021-08-10 09:55 UTC, GirZ0n approved these changes
:+1:

2021-08-10 13:01 UTC, merged