`print_review.py` refactoring
hyperskill/hyperstyle pull request #96
Opened 2021-08-04 14:23 UTC by GirZ0n

**Changes**:
1) Renamed `ReviewResult` -> `GeneralReviewResult`.
2) Added `ReviewResult` from which `GeneralReviewResult` and `FileReviewResult` are now inherited.
3) Put common code when printing `GeneralReviewResult` in different formats in the `convert_review_result_to_json_dict` function.
4) Also prepared the code for further addition of difficulty levels.
5) Fixed the test: now the json schema is checked more strictly.

2021-08-09 07:56 UTC, nbirillo requested changes
Great! I have a question:
- Why you deleted test_multi_file_project.py and test_single_file_json_format.py? These tests are connected to different cases (one file and several files). We need these tests

2021-08-09 07:56 UTC, nbirillo commented on src/python/review/reviewers/review_result.py
> +class GeneralReviewResult(ReviewResult):
Can we add small comments with descriptions for different ReviewResult classes?

2021-08-09 08:10 UTC, GirZ0n commented
@nbirillo I merged `test_multi_file_project.py` and `test_single_file_json_format.py` into one file `test_json_format.py` :slightly_smiling_face:

2021-08-10 09:00 UTC, nbirillo commented
Sorry, I missed it

2021-08-10 13:25 UTC, nbirillo approved these changes
Great, Thank you!

2021-08-10 13:25 UTC, merged